name: Run Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-flask-app:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Specify the Python version you need

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install -r requirements.txt  # Install the dependencies

    # Run Flask application
    - name: Run Flask app
      env:
        FLASK_APP: app.py
      run: |
        flask run --host=0.0.0.0 --port=5000 &  # Run Flask in the background
        sleep 10  # Give Flask some time to start up
        curl http://127.0.0.1:5000  # Test the Flask app with a request

    # Optionally: Run your tests (if you have them)
    - name: Run tests
      run: |
        pytest  # Replace with your test command
